#!/bin/bash

command_exists () {
    type "$1" &> /dev/null ;
}

if command_exists mvn
then
    MVN="mvn"
else
    echo "Please install Maven"
    exit
fi

MAIN_CLASS="eu.monnetproject.translation.fidel.Fidel"
shift
ARGS=$@

ionice -c 3 nice mvn -q exec:java -Dexec.mainClass="$MAIN_CLASS" -Dexec.args="$ARGS"
